/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CatchUpRouteImport } from './routes/catch-up'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DayDateRouteImport } from './routes/day.$date'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CatchUpRoute = CatchUpRouteImport.update({
  id: '/catch-up',
  path: '/catch-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDateRoute = DayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catch-up': typeof CatchUpRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/profile': typeof ProfileRoute
  '/day/$date': typeof DayDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catch-up': typeof CatchUpRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/profile': typeof ProfileRoute
  '/day/$date': typeof DayDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catch-up': typeof CatchUpRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/profile': typeof ProfileRoute
  '/day/$date': typeof DayDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catch-up'
    | '/dashboard'
    | '/export'
    | '/profile'
    | '/day/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catch-up'
    | '/dashboard'
    | '/export'
    | '/profile'
    | '/day/$date'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/catch-up'
    | '/dashboard'
    | '/export'
    | '/profile'
    | '/day/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CatchUpRoute: typeof CatchUpRoute
  DashboardRoute: typeof DashboardRoute
  ExportRoute: typeof ExportRoute
  ProfileRoute: typeof ProfileRoute
  DayDateRoute: typeof DayDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catch-up': {
      id: '/catch-up'
      path: '/catch-up'
      fullPath: '/catch-up'
      preLoaderRoute: typeof CatchUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$date': {
      id: '/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof DayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CatchUpRoute: CatchUpRoute,
  DashboardRoute: DashboardRoute,
  ExportRoute: ExportRoute,
  ProfileRoute: ProfileRoute,
  DayDateRoute: DayDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
